# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Composure < Formula
  desc "Deploy docker-compose files to multiple hosts via SSH with Composure"
  homepage "https://github.com/sprisa/composure"
  version "0.0.1"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sprisa/composure/releases/download/v0.0.1/composure_Darwin_x86_64.tar.gz"
      sha256 "650e3d28da0b71f7cef53a76d5cb11bc27a90518dbd51b8f38ca4e17e4288c21"

      def install
        bin.install "composure"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sprisa/composure/releases/download/v0.0.1/composure_Darwin_arm64.tar.gz"
      sha256 "44ebe06c909f6a460c1da651a8efe9fbe385d697f4af25c4a2b1c602f8d77ace"

      def install
        bin.install "composure"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sprisa/composure/releases/download/v0.0.1/composure_Linux_x86_64.tar.gz"
      sha256 "c9d2e92329e9d6973242fc03674e964b2ee4639e62263643e0facd6d42c4f3d5"
      def install
        bin.install "composure"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sprisa/composure/releases/download/v0.0.1/composure_Linux_arm64.tar.gz"
      sha256 "12ff2f22fb1710a261e6fcc4da2a3e074b8f3c0164798673f44da20a6884fac3"
      def install
        bin.install "composure"
      end
    end
  end
end
