# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localhost < Formula
  desc "Local development certs (TLS) for https services on localhost"
  homepage "https://svc.host"
  version "1.0.0"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sprisa/localhost/releases/download/v1.0.0/localhost_Darwin_x86_64.tar.gz"
      sha256 "260f926f543a7c7d6c247e57cecd1f01d218320bad7287c3b383cc9344fc4b15"

      def install
        bin.install "localhost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sprisa/localhost/releases/download/v1.0.0/localhost_Darwin_arm64.tar.gz"
      sha256 "0b70e79d1ae92877bb2bea204aa1c0f27da0d05f073aa2da0a57a96288cbd58a"

      def install
        bin.install "localhost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sprisa/localhost/releases/download/v1.0.0/localhost_Linux_x86_64.tar.gz"
      sha256 "7d9163ae1d38c9d9e19813eea549de298cb66b7de28163cb878b877e0d695a72"
      def install
        bin.install "localhost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sprisa/localhost/releases/download/v1.0.0/localhost_Linux_arm64.tar.gz"
      sha256 "2ffe961af6fc73819f205ed32a818740286a14a0121a2e5f59ac5c3339e1bf79"
      def install
        bin.install "localhost"
      end
    end
  end
end
